# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build SetHITs (Coq 8.15.0)
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      # Then checkout UniMath in this folder
      - name: Checkout UniMath.
        uses: actions/checkout@v3
        with:
          repository: UniMath/UniMath
          clean: false
          path: .

      # Checkout SetHITs into SetHITs/
      - name: Checkout SetHITs.
        uses: actions/checkout@v3
        with:
          path: SetHITs

      - name: Install OCaml.
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.0
          dune-cache: true
      - run: opam pin add dune 3.5.0
        # We need to set DUNE_CACHE_STORAGE_MODE to copy,
        # otherwise we have to recompile coq every run (opam sandboxing issue).
      - name: Install Coq 8.15.0.
        run: |
          sudo apt-get update
          sudo apt-get install coq
          coqc --version

        # SetHITs is built using the flags specified in code/dune.
      - name: Compile SetHITs.
        run: opam exec -- dune build SetHITs --display=short --cache=enabled --error-reporting=twice
